import Lake
open Lake DSL

package «SylvaFormalization» where
  leanOptions := #[
    ⟨`pp.unicode.fun, true⟩,
    ⟨`pp.proofs.withType, false⟩
  ]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "8a178386ffc0f5fef0b77738bb5449d50efeea95"

@[default_target]
lean_lib «SylvaFormalization» where
  roots := #[
    `BCSTherory,
    `BerryConnection,
    `BerryCurvature,
    `BlochTheorem,
    `ChernNumber,
    `ChernSimons,
    `CondensedMatter.Superconductivity,
    `ContinuumLimit,
    `CookLevin.SAT,
    `Cosmology.DarkEnergy,
    `Cosmology.Inflation,
    `DeterminantComplexity,
    `EinsteinCartan,
    `FifteenConstants,
    `FourForcesUnification,
    `GaugeTheory,
    `GraphTheoreticCharge,
    `Hodge,
    `InformationGeometry,
    `NPClass.PolynomialTime,
    `PhysicalChemistry.ReactionNetwork,
    `QuantumChemistry.Hamiltonian,
    `QuantumChemistry.QuantumMasterEquation,
    `QuantumChemistry.HuckelModel,
    `QuantumChemistry.PartitionFunction,
    `QuantumChemistry.QuantumPhotosynthesis,
    `RiemannHypothesis,
    `SAT,
    `StandardModel.Basic,
    `StringTheory.Basic,
    `SylvaInfrastructure,
    `TopologicalInsulator,
    `NavierStokes,
    `NavierStokes_DEEP_COMPLETED,
    `ZetaVerifier_backup,
    `SYLVA_AdS_CFT,
    `InterdisciplinaryBridge,
    `TopologicalStatMech,
    `GaugeGravityCorrespondence,
    `ComplexityPhysicalSystems,
    `CosmologicalThermodynamics,
    `QuantumBiologyBridge,
    `MachineLearningPhysics,
    `NumberTheoryPhysics,
    `MathematicalTools.ProofPatternLibrary,
    `SYLVA_Hierarchy,
    `SYLVA_Meta,
    `SYLVA_Emergence,
    `SYLVA_Symmetry,
    `SYLVA_Scale,
    `SYLVA_Incompleteness,
    `SYLVA_Information,
    `SYLVA_Computability,
    `SYLVA_Dynamics,
    `SYLVA_Causality,
    `SYLVA_Duality,
    `SYLVA_Geometry,
    `TopologicalQuantumComputing,
    `SYLVA_Language,
    `SYLVA_Complexity,
    `SYLVA_Observation,
    `SYLVA_Matter,
    `SYLVA_Life,
    `SYLVA_Space,
    `SYLVA_Network,
    `SYLVA_OptimalControl,
    `SYLVA_Scaling,
    `SYLVA_Feedback,
    `SYLVA_CollectiveIntelligence,
    `SYLVA_Resilience,
    `SYLVA_Evolution,
    `SYLVA_Creativity,
    `SYLVA_ConnectionLaws,
    `SYLVA_HierarchyOfSciences,
    `SYLVA_ResearchProblems,
    `SYLVA_CrossModuleTheorems,
    `SYLVA_UnifiedPhysics,
    `SYLVA_CrossReferences,
    `SYLVA_QuantumChaos,

    -- v6.0 Extension Modules (2026-07-22)
    `SYLVA_UniversalSymmetry,
    `SYLVA_ConsciousnessBridge,
    `SYLVA_QuantumInformationUnity,
    `SYLVA_CosmologicalConstant,
    `SYLVA_DarkSector,


    `TOE_SYLVA_Wave3_ComprehensiveProofs,

    -- v7.0 Extension Modules
    `SYLVA_Sustainability,
    `SYLVA_Ethics,
    `SYLVA_ComplexityTheory,
    `SYLVA_QuantumGravity,
    `SYLVA_CategoryTheory,
    `SYLVA_HomotopyType,
    `SYLVA_TensorNetwork,
    `SYLVA_RenormalizationGroup,
    `SYLVA_QuantumErrorCorrection,
    `SYLVA_InformationGeometry,
    `SYLVA_OperatorAlgebras,
    `SYLVA_NoncommutativeGeometry,
    `SYLVA_GeometricQuantization,
    `SYLVA_ToposTheory,
    `SYLVA_FreeEnergyPrinciple,
    `SYLVA_SyntheticDifferentialGeometry,
    `SYLVA_SpectralTheory,
    `SYLVA_ExperimentalPredictions,
    `SYLVA_Falsifiability,
    `SYLVA_MathematicalRigor,
    `SYLVA_TimeAsymmetry,
    `SYLVA_ScaleBridging,
    `SYLVA_PhysicalInterpretation,
    `SYLVA_ComputationalComplexity,
    `SYLVA_Underdetermination,
    `SYLVA_ObserverDependence,
    `SYLVA_MathematicalPlatonism,
    `SYLVA_AlgebraicTopology,
    `SYLVA_NumberTheory,
    `SYLVA_KTheory,
    `SYLVA_StringTheory,
    `SYLVA_LoopQuantumGravity,
    `SYLVA_BlackHoleThermodynamics,
    `SYLVA_AlgorithmicInformation,
    `SYLVA_SelfOrganizedCriticality,
    `SYLVA_CausalInference,
    `SYLVA_QuantumShannon,
  ]
