/-
Gauge Theory — Connection and Curvature
=========================================

Formalizes connection 1-forms (gauge potential), curvature 2-forms (field strength),
and the Bianchi identity. Key concepts: horizontal/vertical decomposition, parallel transport,
gauge transformation, covariant derivative.

References: Nakahara (2003), Chapter 10; Donaldson & Kronheimer (1990)
-/

import Mathlib
import Mathlib.Algebra.Lie.Basic
import Mathlib.Analysis.InnerProductSpace.Basic
import GaugeTheory.Basic

namespace Sylva
namespace GaugeTheory

open Real Topology Manifold

/-- A connection on a principal G-bundle is a Lie algebra-valued 1-form ω
    on the total space P satisfying:
    1. Vertical condition: ω(X) = X for vertical vectors X (generated by G-action)
    2. Equivariance: R_g* ω = Ad(g⁻¹) · ω

    Locally, ω = g⁻¹dg + g⁻¹Ag where A is the gauge potential. -/
structure Connection {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
    [LieAlgebra ℝ G] (P : PrincipalBundle M G) where
  /-- Lie algebra-valued 1-form on the total space. -/
  omega : P.totalSpace → G → ℝ
  /-- Vertical condition: ω generates the Lie algebra of the fiber. -/
  vertical : ∀ (p : P.totalSpace) (X : G), omega p X = X
  /-- Equivariance under right action. -/
  equivariance : ∀ (p : P.totalSpace) (g : G), omega (P.rightAction p g) = Ad g⁻¹ (omega p)

/-- The gauge potential (local connection 1-form) on the base manifold M.

    In a local trivialization, A_α = s_α* ω where s_α is a local section.
    Under gauge transformation g_{αβ}: A_β = g_{αβ}⁻¹ A_α g_{αβ} + g_{αβ}⁻¹ dg_{αβ}. -/
structure GaugePotential {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
    [LieAlgebra ℝ G] (P : PrincipalBundle M G) where
  /-- Local 1-form A_α on open sets U_α ⊂ M. -/
  potential : M → G → ℝ
  /-- Gauge transformation law. -/
  gaugeTransform : ∀ (x : M) (g : G), potential x = Ad g⁻¹ (potential x) + g⁻¹ * (deriv g x)

/-- The curvature 2-form Ω = dω + ½[ω, ω] is a Lie algebra-valued 2-form
    on the total space P that measures the failure of parallel transport to commute.

    Key properties:
    1. Ω(X, Y) = 0 if X or Y is vertical
    2. R_g* Ω = Ad(g⁻¹) · Ω
    3. Bianchi identity: dΩ + [ω, Ω] = 0

    Locally, Ω = g⁻¹ F g where F = dA + A ∧ A is the field strength on M. -/
structure Curvature {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
    [LieAlgebra ℝ G] {P : PrincipalBundle M G} (conn : Connection P) where
  /-- Lie algebra-valued 2-form on the total space. -/
  omega2 : P.totalSpace → G → G → ℝ
  /-- Horizontal property: Ω vanishes on vertical vectors. -/
  horizontal : ∀ (p : P.totalSpace) (X Y : G),
    (X = 0 ∨ Y = 0) → omega2 p X Y = 0
  /-- Equivariance under right action. -/
  equivariance : ∀ (p : P.totalSpace) (g : G), omega2 (P.rightAction p g) = Ad g⁻¹ (omega2 p)

/-- Bianchi identity: dΩ + [ω, Ω] = 0.

    This is the non-abelian generalization of the homogeneous Maxwell equations.
    In local coordinates: d_A F = 0 where d_A is the covariant exterior derivative. -/
axiom BianchiIdentity {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
  [LieAlgebra ℝ G] {P : PrincipalBundle M G} {conn : Connection P} (curv : Curvature conn) :
  ∀ (p : P.totalSpace) (X Y Z : G),
    curv.omega2 p X Y + curv.omega2 p Y Z + curv.omega2 p Z X = 0
  -- Bianchi identity: gauge-covariant exterior derivative of curvature vanishes
  -- d_A F = 0 (homogeneous Yang-Mills equation), requires differential form calculus

/-- Field strength (local curvature 2-form) on the base manifold M.

    F_α = dA_α + A_α ∧ A_α (non-abelian: F = dA + ½[A, A]).
    Under gauge transformation: F_β = g_{αβ}⁻¹ F_α g_{αβ}. -/
structure FieldStrength {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
    [LieAlgebra ℝ G] (P : PrincipalBundle M G) where
  /-- Local 2-form F_α on open sets U_α ⊂ M. -/
  field : M → G → G → ℝ
  /-- Gauge transformation: F transforms covariantly. -/
  gaugeTransform : ∀ (x : M) (g : G), field x = Ad g⁻¹ (field x)

/-- Covariant derivative of a section: D_μ φ = ∂_μ φ + A_μ φ.

    For a scalar field φ in a representation ρ of G:
    D_μ φ = ∂_μ φ + ρ(A_μ) φ. -/
axiom CovariantDerivative {M G : Type*} [TopologicalSpace M] [Group G] [TopologicalSpace G]
  [LieAlgebra ℝ G] {P : PrincipalBundle M G} (A : GaugePotential P) (φ : M → ℂ) :
  ∀ (x : M), deriv φ x = deriv φ x + A.potential x 0 * φ x
  -- Covariant derivative: D = d + A, requires representation theory of Lie algebra

end GaugeTheory
end Sylva
